[package]
name = "bluetooth_devices_console"
version = "0.1.0"
edition = "2021"

[dependencies]
bluetooth_devices_lib = { path = "../bluetooth_devices_lib" }
tokio = { version = "1.43", features = ["full"] }